
server:  
  port: 8088
  session-timeout: 30
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /WaterResponseSystem

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署



#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#characterEncoding=UTF-8
spring: 
  datasource:  
    url: jdbc:mysql://localhost:3306/jqm_water_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  aop: 
    proxy-target-class: true
  jpa:  
    database: MYSQL
    show-sql: false
    hibernate:  
      ddl-auto: update
      #naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  activemq:
    broker-url: tcp://127.0.0.1:61616
    in-memory: false
    pool:
      enabled: true           #true表示使用连接池
      max-connections: 5     #连接池最大连接数
      idle-timeout: 30000     #空闲的连接过期时间，默认为30秒
      expiry-timeout: 0       #强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never

mybatis:
  type-aliases-package: com.jqmkj.WaterResponseSystem.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
     cache-enabled: true
     #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
     map-underscore-to-camel-case: true


mapper:
  mappers: com.jqmkj.WaterResponseSystem.basemapper.BaseMapper
  identity: MYSQL


file:
  localPath: D:/photo/
  loadPath: /files/**

